### ISSUE TITLE
Installed...it broke Catplot

### ISSUE THREAD

**Issue by EvanWalkerPoliSci** [aarondwolf/catcibar#1]
Gave this a whirl today. The only thing that happened was it completely broke my ability to use Catplot. 

Somehow, it now only graphs one singular bar no matter the Syntax. Fresh uninstall and install doesn't even fix it lord knows what happened. 

Any idea how to fix this?

**Comment by aarondwolf** [comment]
Interesting. Any chance you have a code example? I haven’t used it in a
while so it’s entirely possible it doesn’t play nice with a new version of
Stata. But it doesn’t override any default settings, so not sure how it
would affect other commands. Let me know what you did and I’ll see if I can
figure it out tomorrow!


Thanks,

Aaron

**Comment by aarondwolf** [comment]
I have tried the MWE from my files, as well as installed used catplot (`net install catplot, from("http://fmwww.bc.edu/RePEc/bocode/c")`), and everything is working fine on my end (Stata 17 MP). Code is below:

```

. clear

. sysuse nlsw88
(NLSW, 1988 extract)

. catcibar wage, over(collgrad) by(smsa) mlabel(mean)

. sysuse auto, clear
(1978 automobile data)

. catplot, over(rep78)

. 
```
The resulting graphs are as expected.

Can you provide a MWE on your end and I can see if I can replicate the problem?

**Comment by EvanWalkerPoliSci** [comment]
Hi Aaron, 

I was able to remedy this today. My hypothesis is something seemed to have happened when I updated to Stata 18 with my .ado files. Re updating, all my packages seems to have fixed whatever was going on here. Everything has been working fine since. 

Unsure what happened. If I bump into it again I will post a trace log here.

**Comment by aarondwolf** [comment]
Okay! Marking this as resolved for now. Feel free to open a new issue if it arises again. Thanks!

**Comment by EvanWalkerPoliSci** [comment]
As a follow up here, NOT on your end at all Aaron, catplot had a small bug that is now fixed.
